#!/bin/bash
# 脚本安装MySQL-python
U_V1=`python -V 2>&1|awk '{print $2}'|awk -F '.' '{print $1}'`
U_V2=`python -V 2>&1|awk '{print $2}'|awk -F '.' '{print $2}'`
number=$U_V1$U_V2
if [ `uname -i` == 'x86_64' ]
then
    system_bit=_amd64
else
    system_bit=32
fi
curl 'https://download.lfd.uci.edu/pythonlibs/c3ylw7lc/mysqlclient-1.3.12-cp'$number'-cp'$number'm-win'$system_bit'.whl' -o 'mysqlclient.whl'
pip install 'mysqlclient.whl'' && \
rm 'mysqlclient.whl'
pip install -r requirements.txt --timeout 3600 && \
cd static && \
npm install && \
rm build -rf && \
npm run build && \
cp images build/images -r