#!/bin/bash
mode='full'
killall(){
    echo "运行终止"
    kill -9 $pid
}
trap 'killall' INT
net start mysql
while getopts ":abf" opt
do  
    case $opt in 
        a)
        mode='full'
        ;; 
        b)
        mode='back'
        ;;  
        f)
        mode='front'
        ;;
        ?) 
        echo "unkwown parameter $opt $OPTARG"  
        exit 1;;  
    esac  
done
if [ $mode == 'full' ]
then
# ./install
python run.py&
pid=$!
cd static && \
npm start
elif [ $mode == 'back' ]
then
python run.py
else
cd static && \
npm start
fi
