#!/bin/bash
while getopts ":a:m:" opt
do  
    case $opt in  
        a)  
        add_files=$OPTARG
        ;;  
        m)  
        message=$OPTARG
        ;;  
        ?) 
        echo "unkwown parameter $opt $OPTARG"  
        exit 1;;  
    esac  
done
# pip freeze > requirements.txt
if [ -z add_files ]
then
    git add *
else
    git add $add_files
fi
if [ -z message ]
then
    git commit -m "auto commit"
else
    git commit -m $message
fi
